apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-data
  namespace: code-quality
spec:
  storageClassName: monitoring-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-database
  namespace: code-quality
spec:
  storageClassName: monitoring-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi