apiVersion: v1
kind: Namespace
metadata:
  name: code-quality

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-data
  namespace: code-quality
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: code-quality
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube:9.9-community
        ports:
        - containerPort: 9000
        env:
        - name: SONAR_JDBC_URL
          value: jdbc:postgresql://devops-toolchain-db:5432/sonar
        - name: SONAR_JDBC_USERNAME
          valueFrom:
            secretKeyRef:
              name: sonarqube-db-credentials
              key: username
        - name: SONAR_JDBC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sonarqube-db-credentials
              key: password
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "1000m"
        volumeMounts:
        - name: data
          mountPath: /opt/sonarqube/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: sonarqube-data

---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: code-quality
spec:
  type: LoadBalancer
  ports:
  - port: 9000
    targetPort: 9000
  selector:
    app: sonarqube
---
apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-db-credentials
  namespace: code-quality
type: Opaque
data:
  username: c29uYXI=  # sonar
  password: c29uYXJwYXNz  # sonarpass 