apiVersion: v1
kind: Secret
metadata:
  name: prometheus-grafana
  namespace: monitoring
type: Opaque
data:
  admin-user: YWRtaW4=        # 'admin' in base64
  admin-password: YWRtaW4xMjM= # 'admin123' in base64
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: prometheus-grafana
              key: admin-user
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: prometheus-grafana
              key: admin-password
        - name: GF_AUTH_BASIC_ENABLED
          value: "true"
        - name: GF_AUTH_DISABLE_LOGIN_FORM
          value: "false"
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
        volumeMounts:
          - name: dashboards
            mountPath: /var/lib/grafana/dashboards
      volumes:
        - name: dashboards
          configMap:
            name: grafana-dashboards
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-grafana
  namespace: monitoring
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: grafana
