apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-pushgateway
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: prometheus-pushgateway
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus-pushgateway
    spec:
      containers:
      - name: pushgateway
        image: prom/pushgateway:v1.6.0
        ports:
        - containerPort: 9091
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-pushgateway
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
  - port: 9091
    targetPort: 9091
  selector:
    app: prometheus-pushgateway
