apiVersion: v1
kind: Service
metadata:
  name: prometheus-pushgateway
  namespace: monitoring
spec:
  type: LoadBalancer
  ports:
    - port: 9091
      targetPort: 9091
      protocol: TCP
  selector:
    app: prometheus-pushgateway
