name: CI/CD Pipeline
on:
  push:
    branches: 
      - main
      - master
  pull_request:
    branches: 
      - main
      - master

env:
  PROJECT_ID: devops-toolchain-456502
  GKE_CLUSTER: devops-toolchain-cluster
  GKE_ZONE: us-central1
  REGISTRY: us-central1-docker.pkg.dev/devops-toolchain-456502/devops-toolchain

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      checks: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Google Cloud SDK and kubectl
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    # Get GKE Credentials
    - name: Get GKE Credentials
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER --region $GKE_ZONE --project $PROJECT_ID

    # Build Docker Image
    - name: Build Docker Image
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t "${REGISTRY}/app:${IMAGE_TAG}" -t "${REGISTRY}/app:latest" .

    # Push Docker Image
    - name: Push Docker Image
      run: |
        REGISTRY_LOWERCASE=$(echo "$REGISTRY" | tr '[:upper:]' '[:lower:]')
        if ! docker push $REGISTRY_LOWERCASE/app:$GITHUB_SHA; then
          echo "Failed to push image"
          exit 1
        fi
        docker push $REGISTRY/app:latest

    # Create Namespace
    - name: Create Namespace
      run: |
        kubectl create namespace dev --dry-run=client -o yaml | kubectl apply -f -